### ISSUE TITLE
Follow the godot style guide

### ISSUE THREAD

**Issue by KoB-Kirito** [majikayogames/SimpleTerrain#3]
Could you follow the style guide? Especially the snake_case folder and file names?
https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_styleguide.html

**Comment by majikayogames** [comment]
Not high on my to do list but if someone else wants to make a PR for this I'll accept it. I want the add-on itself and its folder to remain SimpleTerrain though because that's how I like to name my add-ons. Not gonna change all of them. I usually do SimpleAddonName.

**Comment by KoB-Kirito** [comment]
That's the main thing bothering me. Why not stay with the convention. It's there to unify things. Instead everybody brews their own brew.

It's there for a reason. Changes in casing can f up github. It's anoying when working with teams.

Do as you like, but in the end it's what caused us to not use this addon.

**Comment by majikayogames** [comment]
You are free to fork it. It's just something i made for myself. You can change the name and even the license, it's public domain.
